[project]
name = "maf02-responses"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agent-framework>=1.0.0b251216",
    "azure-ai-projects>=2.0.0b1",
    "azure-identity>=1.26.0b1",
    "python-dotenv>=1.2.1",
]
