[project]
name = "maf04-aifoundry-v2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "azure-ai-projects>=2.0.0b2",
    "azure-identity>=1.26.0b1",
    "openai>=2.9.0",
]
