[project]
name = "agent-with-hosted-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agent-framework>=1.0.0b251218",
    "azure-ai-agentserver-agentframework==1.0.0b7",
]
